Implement remotedogudescriptorrepository
cloudogu/remote-dogu-descriptor-lib pull request #2
Opened 2024-11-05 15:32 UTC by nroeske

Resolves #1

2024-11-07 07:08 UTC, nhinze23 requested changes

2024-11-07 07:08 UTC, nhinze23 commented on Jenkinsfile
> +        if (env.CHANGE_TARGET) {
Like in the commons-lib: Delete this

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +	body, err := ioutil.ReadAll(resp.Body)
use `io.ReadAll` here

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +		dogu, version, err := core.ReadDoguFromString(string(body))
dogu collides with the package name

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +// Get returns the detail about a dogu from the remote server.
```suggestion
// GetLatest returns the detail about the latest dogu from the remote server by name.
```

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +// is given then the newest version will be returned.
```suggestion
// Get returns a version specific detail about the dogu.
```

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +func (r *httpRemote) Get(context context.Context, doguVersion dogu.QualifiedDoguVersion) (*core.Dogu, error) {
```suggestion
func (r *httpRemote) Get(_ context.Context, doguVersion dogu.QualifiedDoguVersion) (*core.Dogu, error) {
```

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +func (r *httpRemote) GetLatest(context context.Context, name dogu.QualifiedDoguName) (*core.Dogu, error) {
```suggestion
func (r *httpRemote) GetLatest(_ context.Context, name dogu.QualifiedDoguName) (*core.Dogu, error) {
```

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +	requestUrl := r.urlSchema.Get(string(name.SimpleName))
The namespace is missing here. You can also validate the name.

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +	requestUrl := r.urlSchema.GetVersion(string(doguVersion.Name.SimpleName), doguVersion.Version.Raw)
The namespace is missing here. You can also validate the name.

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +			return nil, errors.Wrapf(err, "failed to parse proxy url %s", proxyURLString)
Use `fmt.Errorf()` from std lib instead of `errors.Wrapf()` because `github.com/pkg/errors` is no longer maintained.

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +func (r *httpRemote) receiveDoguFromRemoteOrCache(requestUrl string, cacheDirectory string) (*core.Dogu, error) {
We should refactor this whole routine. If `useCache` is true we should **first** query the cache and if no dogu is found then we can make that call to the external dogu registry.

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +			return r.requestWithoutCredentialsFirst(requestUrl, &remoteDogu)
I would refactor this logic too. One can just call `requestWithoutCredentials` and check if an error occurs. If yes try with `request`. This would improve the readability.

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +var errUnauthorized = errors.New("401 unauthorized, please login to proceed")
Maybe these errors should be in the commons lib. Or the errors from the commons lib should be here.

2024-11-07 07:08 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +		return "error"
The string `error` acts not really as a further explanation. I think `err.Error()` would fit better here.
Refactor signature of return values like this: (body string, err error)

2024-11-07 15:48 UTC, cesmarvin commented on repository/httpRemoteRepository.go
> +	resp, err := r.client.Do(request)
🚫 **[checkstyle]** <bodyclose> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>response body must be closed
<!-- __reviewdog__:ChAzZjUxMzRiNWM5ZDNlNzVhEgpjaGVja3N0eWxl -->

2024-11-11 10:11 UTC, cesmarvin commented on repository/httpRemoteRepository.go
> +	resp, err := r.client.Do(request)
🚫 **[checkstyle]** <bodyclose> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>response body must be closed
<!-- __reviewdog__:ChAyNGFlZWJhZWRmMWI0MGZhEgpjaGVja3N0eWxl -->

2024-11-11 10:19 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +			return &core.Dogu{}, fmt.Errorf("failed to read from remote registry and cache: %w", err)
```suggestion
			return &core.Dogu{}, fmt.Errorf("failed to read dogu from cache %s: %w", cacheFile, err)
```

2024-11-11 10:20 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +	return &core.Dogu{}, fmt.Errorf("useCache is not activated")
```suggestion
	return nil, fmt.Errorf("useCache is not activated")
```

2024-11-11 10:27 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +			requestErr := r.requestWithoutCredentialsFirst(requestUrl, &remoteDogu)
We should discuss this. Why should we always first try a request without credentials?

2024-11-13 10:34 UTC, cesmarvin commented on repository/httpRemoteRepository.go
> +	resp, err := r.client.Do(request)
🚫 **[checkstyle]** <bodyclose> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>response body must be closed
<!-- __reviewdog__:ChA2M2Y5YmQyODVjN2Q4OTZhEgpjaGVja3N0eWxl -->

2024-11-13 14:46 UTC, cesmarvin commented on repository/httpRemoteRepository.go
> +	resp, err := r.client.Do(request)
🚫 **[checkstyle]** <bodyclose> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>response body must be closed
<!-- __reviewdog__:ChBhMjNlOWJkZmJlNzBiODEyEgpjaGVja3N0eWxl -->

2024-11-13 15:14 UTC, cesmarvin commented on repository/httpRemoteRepository.go
> +	resp, err := r.client.Do(request)
🚫 **[checkstyle]** <bodyclose> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>response body must be closed
<!-- __reviewdog__:ChBlZmVkODU5YjcxZDE1MDBhEgpjaGVja3N0eWxl -->

2024-11-14 14:52 UTC, cesmarvin commented on repository/httpRemoteRepository.go
> +	resp, err := r.client.Do(request)
🚫 **[checkstyle]** <bodyclose> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>response body must be closed
<!-- __reviewdog__:ChA4MTcyMzBiOWJlNWI2M2MzEgpjaGVja3N0eWxl -->

2024-11-14 14:52 UTC, cesmarvin commented on repository/httpRemoteRepository.go
> +		if err != nil {
🚫 **[checkstyle]** <staticcheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>SA9003: empty branch
<!-- __reviewdog__:ChBmZTk5ODU4MjFmZGJkNDY4EgpjaGVja3N0eWxl -->

2024-11-15 08:31 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +		if err != nil {
log error here

2024-11-15 08:40 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +	var remoteDogu, err = r.readCachedDogu(dirname)
You are loosing the initial cache error in the retry. Rename the error and wrap it.

2024-11-15 08:41 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +			return &core.Dogu{}, fmt.Errorf("failed to write dogu to cache: %w", err)
Use the generic error from commons

2024-11-15 08:43 UTC, nhinze23 commented on repository/httpRemoteRepository.go
> +	//nolint:forcetypeassert
```suggestion
```

2024-11-15 08:51 UTC, nhinze23 commented
Unit tests are failing

2024-11-15 10:08 UTC, meiserloh requested changes

2024-11-15 10:08 UTC, meiserloh commented on repository/httpRemoteRepository.go
> +		})
Retry only in clients to prevent multiple retrying

2024-11-15 10:08 UTC, meiserloh commented on repository/httpRemoteRepository.go
> +		return nil, fmt.Errorf("qualified dogu name is not valid (name: %s): %w", name.String(), err)
this should be a generic Error as well

2024-11-15 10:08 UTC, meiserloh commented on repository/httpRemoteRepository.go
> +			return fmt.Errorf("remote registry returns invalid status: %s: %s", response.Status, furtherExplanation)
Generic Error? (check whole file)

2024-11-15 10:08 UTC, meiserloh commented on repository/remote_http_test.go
> +		mockResp.Body = ioutil.NopCloser(strings.NewReader(`{"status": "forbidden"}`))
`{"status": "forbidden"}` copy paste? Shouldn't it be like "not found" or something?

2024-11-15 10:08 UTC, meiserloh commented on repository/repository_test.go
> +	assert.NotNil(t, got)
what purpose serves this test over the othe one in this file if just "NotNil" is testet?

2024-11-15 10:32 UTC, cesmarvin commented on repository/httpRemoteRepository.go
> +	resp, err := r.client.Do(request)
🚫 **[checkstyle]** <bodyclose> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>response body must be closed
<!-- __reviewdog__:ChAxMjk3NGVkYjI5MDQyZDUxEgpjaGVja3N0eWxl -->

2024-11-15 12:59 UTC, merged